app/panel/__init__.py
from flask import Blueprint

bp = Blueprint("panel", __name__)

from app.panel import routes

app/panel/routes.py
from flask import render_template, request, flash, current_app, Response
from flask_login import login_required
from werkzeug.security import generate_password_hash, check_password_hash

import os
import markdown
import psutil
import socket
import base64
import qrcode
from io import BytesIO

from app.models.user import User
from app.extensions import db
from app.config_tools import get_config, set_config, get_all_extensions, set_extension_status, add_extension, delete_extension, add_ip, delete_ip, get_all_ips, set_whitelist_status, set_blacklist_status

from app.panel import bp


def get_host_ips():
    ips = set()
    for iface_info in psutil.net_if_addrs().values():
        for addr in iface_info:
            if addr.family == socket.AF_INET and not addr.address.startswith("169.254"):
                ips.add(addr.address)

    return sorted(ips)

def get_port():
    return request.host.split(":")[-1]
    
@bp.route("/", methods=["POST", "GET"])
@bp.route("/configuration", methods=["POST", "GET"])
@login_required
def configuration():
    flash("This is a demo instance, so some setting may not be available", "warning")
    sharing_enabled = True if get_config("sharing_enabled") == "True" else False
    if request.method == "POST":
        field = request.form.get("field")
        if field == "sharing_action":
            sharing_action = request.form.get("sharing_action")
            if sharing_action == "disable":
                set_config("sharing_enabled", "False")
                current_app.logger.info(f"{request.remote_addr} disabled file sharing")
            else:
                set_config("sharing_enabled", "True")
                current_app.logger.info(f"{request.remote_addr} enabled file sharing")
            sharing_enabled = True if get_config("sharing_enabled") == "True" else False
        if field == "allowed_extensions":    
            new_allowed_extensions = request.form.getlist("extension_checkbox")
            for extension in get_all_extensions():
                if extension[0] in new_allowed_extensions and extension[1] == 0:
                    set_extension_status(extension[0], 1)
                elif not extension[0] in new_allowed_extensions and extension[1] == 1:
                    set_extension_status(extension[0], 0)
        if field == "add_extension":
            flash("This can't be changed on a demo instance!", "error")
        if field == "delete_extension":
            flash("This can't be changed on a demo instance!", "error")
        if field == "upload_folder":
            flash("This can't be changed on a demo instance!", "error")
    return render_template("panel/configuration.html", sharing_enabled = sharing_enabled, extensions = get_all_extensions(), upload_folder = get_config("upload_folder"))

@bp.route("/security", methods=["GET", "POST"])
@login_required
def security():
    if request.method == "POST":
        field = request.form.get("field")
        if field == "change_password":
            current_password = request.form.get("current_password")
            new_password = request.form.get("new_password")
            confirm_new_password = request.form.get("confirm_new_password")
            if current_password and new_password and confirm_new_password:
                if check_password_hash(User.query.filter_by(username="admin").first().password, current_password):
                    if new_password == confirm_new_password:
                        flash("This can't be changed on a demo instance!", "error")
                    else:
                        flash("Passwords do not match!", "error")
                else:
                    flash("Password incorrect!", "error")
            else:
                flash("All fields are required!", "error")
        if field == "security_mode":
            flash("This can't be changed on a demo instance!", "error")
        if field == "add_ip":
            add_ip(request.form.get("ip"))
        if field == "delete_ip":
            delete_ip(request.form.get("ip"))
        if field == "edit_whitelist":
            flash("This can't be changed on a demo instance!", "error")
        if field == "edit_blacklist":
            flash("This can't be changed on a demo instance!", "error")
    return render_template("panel/security.html", security_mode=get_config("security_mode"), ips=get_all_ips())

# @bp.route("/docs")
# @login_required
# def docs():
#     readme_path = os.path.join(current_app.root_path, "..", "README.md")
#     with open(readme_path, 'r', encoding='utf-8') as readme:
#         readme_content = readme.read()
#     return render_template("panel/docs.html", readme_content = markdown.markdown(readme_content))

@bp.route("/logs")
@login_required
def logs():
    flash("You can't view logs in the demo mode!", "warning")
    logs_dir = os.path.join(current_app.root_path, "..", "logs")
    return render_template("/panel/logs.html", logs=os.listdir(logs_dir))

# @bp.route("/log/<file>")
# @login_required
# def logviewer(file):
#     log_file = os.path.join(current_app.root_path, "..", "logs", file)
#     with open(log_file, "r") as log:
#         content = log.read()
#     return Response(content, mimetype="text/plain")

@bp.route("/info")
@login_required
def info():
    host_ips=get_host_ips()
    port = get_port()
    
    qrs = list()
    
    for ip in host_ips:
        # if(ip == "127.0.0.1"):
        #     continue
        qr = qrcode.make(f"http://{ip}:{port}")
        buffer = BytesIO()  # ✅ Create an in-memory buffer
        qr.save(buffer, format="PNG")
        qrs.append((ip, base64.b64encode(buffer.getvalue()).decode("utf-8")))
    
    return render_template("panel/info.html", host_ips=host_ips, port=port, qrs = qrs)

app/templates/panel/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FileDrop Panel | {% block title%}{% endblock%}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css"
      type="text/css"
    />
  </head>
  <body class="bg-gray-100 m-0 p-0 dark:bg-slate-900 dark:text-white">
    <button
      id="menuToggle"
      class="sm:hidden fixed top-4 right-4 z-50 p-2 rounded bg-blue-500 text-white"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="size-6"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
        />
      </svg>
      Menu
    </button>

    <div
      id="sidebar"
      class="bg-slate-50 h-screen w-[24%] m-0 p-0 fixed overflow-auto shadow-[0px_4px_6px_0px_rgba(0,_0,_0,_0.1)] rounded-md dark:bg-slate-800 w-full sm:w-[24%] hidden sm:block"
    >
      <p class="pb-4 px-4 my-[1%] text-3xl dark:text-white mt-4">
        FileDrop
        <span
          class="font-bold bg-gradient-to-r from-blue-400 to-blue-600 inline-block text-transparent bg-clip-text"
          >Panel</span
        >
      </p>
      <div class="flex flex-col items-center">
        <a
          href="{{ url_for('panel.configuration') }}"
          class="{% if request.path == '/panel/' or request.path == '/panel/configuration' %} bg-gray-200 dark:bg-slate-600 {% endif %} px-4 py-3 w-[95%] mb-2 rounded-md duration-200 hover:bg-gray-300 flex items-center dark:hover:bg-slate-700"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"
            />
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
            />
          </svg>
          Configuration</a
        >
        <a
          href="{{ url_for('panel.security') }}"
          class="{% if request.path == '/panel/security' %} bg-gray-200 dark:bg-slate-600{% endif %} px-4 py-3 w-[95%] mb-2 rounded-md duration-200 hover:bg-gray-300 flex items-center dark:hover:bg-slate-700"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z"
            />
          </svg>
          Security</a
        >
        <a
          href="{{ url_for('panel.logs') }}"
          class="{% if request.path == '/panel/logs' %} bg-gray-200 dark:bg-slate-600{% endif %} px-4 py-3 w-[95%] mb-2 rounded-md duration-200 hover:bg-gray-300 flex items-center dark:hover:bg-slate-700"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 0 1-2.25 2.25M16.5 7.5V18a2.25 2.25 0 0 0 2.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 0 0 2.25 2.25h13.5M6 7.5h3v3H6v-3Z"
            />
          </svg>

          Logs</a
        >
        <a
          href="https://github.com/staskycia/filedrop/blob/main/README.md"
          target="_blank"
          class="{% if request.path == '/panel/docs' %} bg-gray-200 dark:bg-slate-600{% endif %} px-4 py-3 w-[95%] mb-2 rounded-md duration-200 hover:bg-gray-300 flex items-center dark:hover:bg-slate-700"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M4.26 10.147a60.438 60.438 0 0 0-.491 6.347A48.62 48.62 0 0 1 12 20.904a48.62 48.62 0 0 1 8.232-4.41 60.46 60.46 0 0 0-.491-6.347m-15.482 0a50.636 50.636 0 0 0-2.658-.813A59.906 59.906 0 0 1 12 3.493a59.903 59.903 0 0 1 10.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.717 50.717 0 0 1 12 13.489a50.702 50.702 0 0 1 7.74-3.342M6.75 15a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm0 0v-3.675A55.378 55.378 0 0 1 12 8.443m-7.007 11.55A5.981 5.981 0 0 0 6.75 15.75v-1.5"
            />
          </svg>
          Docs</a
        >
        <a
          href="{{ url_for('panel.info') }}"
          class="{% if request.path == '/panel/info' %} bg-gray-200 dark:bg-slate-600{% endif %} px-4 py-3 w-[95%] mb-2 rounded-md duration-200 hover:bg-gray-300 flex items-center dark:hover:bg-slate-700"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z"
            />
          </svg>
         Sharing manual</a
        >
        <a
          href="{{ url_for('main.logout') }}"
          class="text-white px-4 py-3 w-[95%] mb-2 rounded-md duration-200 bg-red-500 hover:bg-red-600 flex items-center"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 mr-3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M5.636 5.636a9 9 0 1 0 12.728 0M12 3v9"
            />
          </svg>
          Logout</a
        >
      </div>
    </div>
    <div class="ml-[25%] w-[75%] max-sm:mx-auto">
      {% with messages = get_flashed_messages(with_categories=True) %} {% if
      messages %}
      <div class="text-center text-xl text-bold w-[20%] mx-auto">
        {% for cattegory, message in messages %}
        <div
          class="py-4 {% if cattegory == 'error' %} bg-red-200 text-red-700 {% elif cattegory == 'success' %} bg-green-200 text-green-700 {% elif cattegory == 'warning' %} bg-yellow-200 text-yellow-700 {% endif %} rounded-md mb-3"
        >
          {{message}}
        </div>
        {% endfor %}
      </div>
      {% endif %} {% endwith %} {% block content %} {% endblock %}
    </div>

    <script>
      const toggleBtn = document.getElementById("menuToggle");
      const sidebar = document.getElementById("sidebar");

      toggleBtn.addEventListener("click", () => {
        if (window.innerWidth < 640) {
          sidebar.classList.toggle("hidden");
        }
      });
    </script>
  </body>
</html>

app/templates/panel/configuration.html
{% extends "panel/base.html" %} {% block title%} Configuration {% endblock %} {%
block content%}
<div class="flex flex-row flex-wrap gap-[2%] justify-center">
  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Files Reciving</h1>
      <p class="text-lg max-w-[99%]">
        File reciving is currently
        <span class="font-bold"
          >{% if sharing_enabled %} enabled {% else %} disabled {% endif
          %}</span
        >
      </p>
    </div>
    <form method="POST" action="{{url_for('panel.configuration')}}">
      <input class="hidden" type="text" name="field" value="sharing_action" />
      <input
        class="hidden"
        type="text"
        name="sharing_action"
        value="{% if sharing_enabled %}disable{% else %}enable{% endif %}"
      />
      <input
        type="submit"
        class="mb-4 px-14 py-2 rounded-full text-white duration-200 {% if sharing_enabled %}bg-red-500 hover:bg-red-600 active:bg-red-700{% else %}bg-green-500 hover:bg-green-600 active:bg-green-700{% endif %}"
        value="{% if sharing_enabled %} Disable {% else %} Enable {% endif %}"
      />
    </form>
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Allowed Extensions</h1>
    </div>
    <form method="POST" action="{{url_for('panel.configuration')}}">
      <input
        class="hidden"
        type="text"
        name="field"
        value="allowed_extensions"
      />
      <div class="flex flex-col">
        {% for extension in extensions %}
        <div class="flex items-center gap-2 mb-2">
          <input type="checkbox" id="checkbox_{{extension[0]}}"
          name="extension_checkbox" value="{{extension[0]}}" {% if
          extension[1]== 1 %}checked{% endif %} />
          <label for="checkbox_{{extension[0]}}">{{extension[0]}}</label>
        </div>
        {% endfor %}
      </div>
      <input
        type="submit"
        class="mb-4 bg-blue-500 px-14 py-2 rounded-full text-white duration-200 hover:bg-blue-600 active:bg-blue-700"
        value="Update"
      />
    </form>
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Add Extension</h1>
      <p class="text-lg max-w-[99%]">
        Do not include the leading dot, case sensitive
      </p>
    </div>
    <form method="POST" action="{{url_for('panel.configuration')}}">
      <input class="hidden" type="text" name="field" value="add_extension" />
      <input
        type="text"
        class="text-blue-500 placeholder-blue-500 px-[1rem] py-[0.9rem] mb-4 rounded-md duration-150 bg-blue-50 hover:bg-blue-100 focus:bg-blue-200 focus:outline-none border-[2px] border-solid border-blue-500 max-sm:w-[70%] max-sm:h-[40%] dark:bg-blue-950 dark:hover:bg-blue-900 dark:focus:bg-blue-800 dark:placeholder-white dark:text-white"
        placeholder="eg. pdf"
        name="extension"
      /><br />
      <input
        type="submit"
        class="mb-4 bg-green-500 px-14 py-2 rounded-full text-white duration-200 hover:bg-green-600 active:bg-green-700"
        value="Add"
      />
    </form>
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Delete Extension</h1>
      <p class="text-lg max-w-[99%]">
        Do not include the leading dot, case sensitive
      </p>
    </div>
    <form method="POST" action="{{url_for('panel.configuration')}}">
      <input class="hidden" type="text" name="field" value="delete_extension" />
      <input
        type="text"
        class="text-blue-500 placeholder-blue-500 px-[1rem] py-[0.9rem] mb-4 rounded-md duration-150 bg-blue-50 hover:bg-blue-100 focus:bg-blue-200 focus:outline-none border-[2px] border-solid border-blue-500 max-sm:w-[70%] max-sm:h-[40%] dark:bg-blue-950 dark:hover:bg-blue-900 dark:focus:bg-blue-800 dark:placeholder-white dark:text-white"
        placeholder="eg. pdf"
        name="extension"
      /><br />
      <input
        type="submit"
        class="mb-4 bg-red-500 px-14 py-2 rounded-full text-white duration-200 hover:bg-red-600 active:bg-red-700"
        value="Delete"
      />
    </form>
  </div>

<div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Upload Folder</h1>
    </div>
    <form method="POST" action="{{url_for('panel.configuration')}}">
      <input class="hidden" type="text" name="field" value="upload_folder" />
      <input
        type="text"
        class="text-blue-500 placeholder-blue-500 px-[1rem] py-[0.9rem] mb-4 rounded-md duration-150 bg-blue-50 hover:bg-blue-100 focus:bg-blue-200 focus:outline-none border-[2px] border-solid border-blue-500 max-sm:w-[70%] max-sm:h-[40%] dark:bg-blue-950 dark:hover:bg-blue-900 dark:focus:bg-blue-800 dark:placeholder-white dark:text-white"
        value="{{upload_folder}}"
        name="upload_folder"
      /><br />
      <input
        type="submit"
        class="mb-4 bg-blue-500 px-14 py-2 rounded-full text-white duration-200 hover:bg-blue-600 active:bg-blue-700"
        value="Update"
      />
    </form>
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-transparent rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-900"
  >
  </div>
</div>
{% endblock %}

app/templates/panel/docs.html
{% extends "panel/base.html" %}
{% block title%} Docs {% endblock %}
{% block content%}
{{ readme_content | safe }}
{% endblock %}

app/templates/panel/info.html
{% extends "panel/base.html" %} {% block title%} Instance Info {% endblock %} {%
block content%}
<div class="flex flex-row flex-wrap gap-[2%] justify-center">
  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">To share files:</h1>
    </div>
    <ol class="list-decimal list-inside text-left space-y-3">
      <li>Connect to the same Wi-Fi nettwork as the host computer</li>
      <li>
        <div class="mb-2">Navigate to one of the following addresses:</div>
        {% for ip in host_ips %}
        <div class="ml-4 mb-2">
          <code class="bg-gray-300 px-2 py-1 rounded text-sm dark:bg-slate-800"
            >{{ip}}:{{port}}</code
          >
        </div>
        {% endfor %}
        <p class="italic text-sm mt-2 ml-4">
          Note that
          <code class="bg-gray-300 px-2 py-1 rounded text-sm dark:bg-slate-800"
            >127.0.0.1:{{port}}</code
          >
          is only accessible on the host computer.
        </p>
      </li>
      <li>Upload files you want to share</li>
    </ol>
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">QR Code(s)</h1>
      {% for qr in qrs %}
      <div class="my-2">
        <p class="text-lg max-w-[99%]">{{ qr[0] }}</p>
        <img src="data:image/png;base64,{{ qr[1] }}" class="w-[50%] mx-auto" />
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/panel/logs.html
{% extends "panel/base.html" %} {% block title%} Logs {% endblock %} {% block
content%}
<div class="flex flex-row flex-wrap gap-[2%] justify-center">
  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-gray-200 rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-600"
  >
    <div>
      <h1 class="text-2xl mt-4">Available Logs</h1>
    </div>

    {% for log in logs %}

    <p class="mb-4 bg-gray-500 px-14 py-2 rounded-full text-white">{{log}}</p>
    {% endfor %}
  </div>

  <div
    class="w-[48%] min-h-[300px] my-[1%] bg-transparent rounded-md min-w-[350px] flex items-center flex-col justify-evenly text-center dark:bg-slate-900"
  ></div>
</div>
{% endblock %}